import type { Metadata } from "next";
import logo from "@/public/images/logo.png";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Vocab Wars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex  flex-col md:flex-row">
          <div className="hidden  md:flex flex-col  m-1 p-2 w-44 h-full ">
            <Image src={logo} alt="logo"></Image>
            <div className="relative w-full text-gray-200 h-full">
              {/* slider */}
              <div></div>
              {/* Option */}
              <ul>
                <li>Daily</li>
                <li>Contests</li>
              </ul>
            </div>
          </div>

          {children}
        </div>
      </body>
    </html>
  );
}
